USE [master]
GO
/****** Object:  Database [DELIVERYDB]    Script Date: 3/16/2024 8:18:50 PM ******/
CREATE DATABASE [DELIVERYDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DELIVERYDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DELIVERYDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DELIVERYDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DELIVERYDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DELIVERYDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DELIVERYDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DELIVERYDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DELIVERYDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DELIVERYDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DELIVERYDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DELIVERYDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [DELIVERYDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DELIVERYDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DELIVERYDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DELIVERYDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DELIVERYDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DELIVERYDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DELIVERYDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DELIVERYDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DELIVERYDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DELIVERYDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DELIVERYDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DELIVERYDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DELIVERYDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DELIVERYDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DELIVERYDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DELIVERYDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DELIVERYDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DELIVERYDB] SET RECOVERY FULL 
GO
ALTER DATABASE [DELIVERYDB] SET  MULTI_USER 
GO
ALTER DATABASE [DELIVERYDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DELIVERYDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DELIVERYDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DELIVERYDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DELIVERYDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DELIVERYDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DELIVERYDB', N'ON'
GO
ALTER DATABASE [DELIVERYDB] SET QUERY_STORE = OFF
GO
USE [DELIVERYDB]
GO
/****** Object:  Schema [Deliveries]    Script Date: 3/16/2024 8:18:50 PM ******/
CREATE SCHEMA [Deliveries]
GO
/****** Object:  Schema [Lookup]    Script Date: 3/16/2024 8:18:50 PM ******/
CREATE SCHEMA [Lookup]
GO
/****** Object:  Schema [Person]    Script Date: 3/16/2024 8:18:50 PM ******/
CREATE SCHEMA [Person]
GO
/****** Object:  Schema [Schedule]    Script Date: 3/16/2024 8:18:50 PM ******/
CREATE SCHEMA [Schedule]
GO
/****** Object:  Table [Deliveries].[TBL_DELIVERY_ADDRESS]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Deliveries].[TBL_DELIVERY_ADDRESS](
	[DELIVERYADDRESS_ID] [int] IDENTITY(1,1) NOT NULL,
	[DELIVERY_DETAILS_ID] [int] NOT NULL,
	[CITY_ID] [smallint] NOT NULL,
	[STREET] [nvarchar](150) NULL,
	[ROAD] [nvarchar](150) NULL,
	[ZIP] [nvarchar](10) NULL,
	[ADDRESS] [nvarchar](500) NULL,
	[ADDRESSTYPE_ID] [smallint] NULL,
PRIMARY KEY CLUSTERED 
(
	[DELIVERYADDRESS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Deliveries].[TBL_DELIVERY_DETAILS]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Deliveries].[TBL_DELIVERY_DETAILS](
	[DELIVERY_DETAILS_ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDER_ID] [int] NOT NULL,
	[DELIVERY_DATE] [datetime] NULL,
	[DELIVERY_STATUS] [smallint] NULL,
	[CONFIRMATION] [bit] NOT NULL,
	[CONFIRMATION_DATE] [datetime] NULL,
	[CONFIRMATION_NOTE] [nvarchar](500) NULL,
 CONSTRAINT [PK__TBL_DELI__2F3D974290EE1CF0] PRIMARY KEY CLUSTERED 
(
	[DELIVERY_DETAILS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Deliveries].[TBL_DELIVERY_LOGS]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Deliveries].[TBL_DELIVERY_LOGS](
	[LOG_ID] [int] IDENTITY(1,1) NOT NULL,
	[DELIVERY_DETAILS_ID] [int] NOT NULL,
	[ACTIVITY_DATE] [datetime] NOT NULL,
	[ACTIVITY_TYPE] [nvarchar](50) NOT NULL,
	[ACTIVITY_DESCRIPTION] [nvarchar](500) NULL,
	[ACTIVITY_TYPE_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Deliveries].[TBL_ITEMS]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Deliveries].[TBL_ITEMS](
	[ITEMS_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[DESCRIPTION] [nvarchar](255) NULL,
	[PRICE] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ITEMS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Deliveries].[TBL_ORDER_ITEMS]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Deliveries].[TBL_ORDER_ITEMS](
	[ORDER_ITEMS_ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDER_ID] [int] NOT NULL,
	[ITEM_ID] [int] NOT NULL,
	[QUANTITY] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ORDER_ITEMS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Deliveries].[TBL_ORDERS]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Deliveries].[TBL_ORDERS](
	[ORDER_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[ORDER_DATE] [datetime] NOT NULL,
	[TOTAL] [decimal](10, 2) NOT NULL,
	[ORDERSTATUS_ID] [smallint] NULL,
 CONSTRAINT [PK__TBL_ORDE__460A9464729C9ED6] PRIMARY KEY CLUSTERED 
(
	[ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Lookup].[TBL_ACTIVITY_TYPE]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lookup].[TBL_ACTIVITY_TYPE](
	[ACTIVITY_TYPE_ID] [int] NOT NULL,
	[ACTIVITY_TYPE_NAME] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ACTIVITY_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Lookup].[TBL_ADDRESS_TYPE]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lookup].[TBL_ADDRESS_TYPE](
	[ADDRESSTYPE_ID] [smallint] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__TBL_ADDR__C80A7579AF90BB2D] PRIMARY KEY CLUSTERED 
(
	[ADDRESSTYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Lookup].[TBL_DELIVERY_STATUS]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lookup].[TBL_DELIVERY_STATUS](
	[DELIVERYSTATUS_ID] [smallint] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__TBL_ORDE__7A9CE64ABC13E114] PRIMARY KEY CLUSTERED 
(
	[DELIVERYSTATUS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Lookup].[TBL_PERIODS]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lookup].[TBL_PERIODS](
	[PERIOD_ID] [smallint] NOT NULL,
	[NAME] [nvarchar](50) NULL,
	[DESCRIPTION] [nvarchar](250) NULL,
	[OCCURANCE_PERMONTH] [smallint] NULL,
 CONSTRAINT [PK_TBL_PERIOD_LKPT] PRIMARY KEY CLUSTERED 
(
	[PERIOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Lookup].[TBL_SCHEDULE_STATUS]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lookup].[TBL_SCHEDULE_STATUS](
	[SCHEDULESTATUS_ID] [smallint] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__TBL_SCHE__107F9A30181A77EF] PRIMARY KEY CLUSTERED 
(
	[SCHEDULESTATUS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Lookup].[TBL_USER_TYPE]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lookup].[TBL_USER_TYPE](
	[USERTYPE_ID] [smallint] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TBL_USER_TYPE__C80] PRIMARY KEY CLUSTERED 
(
	[USERTYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Person].[TBL_USERS]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Person].[TBL_USERS](
	[USERS_ID] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	[PASSWORDHASH] [nvarchar](50) NOT NULL,
	[EMAIL] [nvarchar](100) NULL,
	[PHONE] [nvarchar](15) NULL,
	[ADDRESS] [nvarchar](255) NULL,
	[USERTYPE_ID] [smallint] NULL,
PRIMARY KEY CLUSTERED 
(
	[USERS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Person].[TBL_USERS_ADDRESS]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Person].[TBL_USERS_ADDRESS](
	[ADDRESS_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[CITY_ID] [smallint] NOT NULL,
	[STREET] [nvarchar](150) NULL,
	[ROAD] [nvarchar](150) NULL,
	[ZIP] [nvarchar](10) NULL,
	[ADDRESS] [nvarchar](500) NULL,
	[ADDRESSTYPE_ID] [smallint] NULL,
PRIMARY KEY CLUSTERED 
(
	[ADDRESS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Schedule].[TBL_SCHEDULER]    Script Date: 3/16/2024 8:18:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Schedule].[TBL_SCHEDULER](
	[SCHEDULER_ID] [int] IDENTITY(1,1) NOT NULL,
	[TO_DATE] [datetime] NOT NULL,
	[FROM_DATE] [datetime] NOT NULL,
	[DELIVERY_SLOT] [nvarchar](50) NOT NULL,
	[ASSIGNED_TO] [int] NULL,
	[NOTE] [nvarchar](500) NULL,
	[PERIOD_ID] [smallint] NULL,
	[SCHEDULESTATUS_ID] [smallint] NULL,
 CONSTRAINT [PK__TBL_SCHE__9FCA8FDFAE0E1E5D] PRIMARY KEY CLUSTERED 
(
	[SCHEDULER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [Deliveries].[TBL_ITEMS] ON 
GO
INSERT [Deliveries].[TBL_ITEMS] ([ITEMS_ID], [NAME], [DESCRIPTION], [PRICE]) VALUES (2, N'Beef with Beetroot', N'Beef with Beetroot', CAST(25.00 AS Decimal(10, 2)))
GO
INSERT [Deliveries].[TBL_ITEMS] ([ITEMS_ID], [NAME], [DESCRIPTION], [PRICE]) VALUES (3, N'Chicket with Banana', N'Chicket with Banana', CAST(20.00 AS Decimal(10, 2)))
GO
INSERT [Deliveries].[TBL_ITEMS] ([ITEMS_ID], [NAME], [DESCRIPTION], [PRICE]) VALUES (4, N'Lamb with Apple', N'Lamb with Apple', CAST(32.00 AS Decimal(10, 2)))
GO
SET IDENTITY_INSERT [Deliveries].[TBL_ITEMS] OFF
GO
INSERT [Lookup].[TBL_ACTIVITY_TYPE] ([ACTIVITY_TYPE_ID], [ACTIVITY_TYPE_NAME]) VALUES (1, N'Adding')
GO
INSERT [Lookup].[TBL_ACTIVITY_TYPE] ([ACTIVITY_TYPE_ID], [ACTIVITY_TYPE_NAME]) VALUES (2, N'Updating')
GO
INSERT [Lookup].[TBL_ACTIVITY_TYPE] ([ACTIVITY_TYPE_ID], [ACTIVITY_TYPE_NAME]) VALUES (3, N'Deleting')
GO
INSERT [Lookup].[TBL_ADDRESS_TYPE] ([ADDRESSTYPE_ID], [NAME]) VALUES (1, N'Home Address')
GO
INSERT [Lookup].[TBL_ADDRESS_TYPE] ([ADDRESSTYPE_ID], [NAME]) VALUES (2, N'Office Address')
GO
INSERT [Lookup].[TBL_DELIVERY_STATUS] ([DELIVERYSTATUS_ID], [NAME]) VALUES (1, N'Upcoming')
GO
INSERT [Lookup].[TBL_DELIVERY_STATUS] ([DELIVERYSTATUS_ID], [NAME]) VALUES (2, N'Delivered')
GO
INSERT [Lookup].[TBL_DELIVERY_STATUS] ([DELIVERYSTATUS_ID], [NAME]) VALUES (3, N'InProcess')
GO
INSERT [Lookup].[TBL_PERIODS] ([PERIOD_ID], [NAME], [DESCRIPTION], [OCCURANCE_PERMONTH]) VALUES (1, N'Monthly', N'Each Month', 1)
GO
INSERT [Lookup].[TBL_PERIODS] ([PERIOD_ID], [NAME], [DESCRIPTION], [OCCURANCE_PERMONTH]) VALUES (2, N'Bi Monthly', N'Twice a Month', 2)
GO
INSERT [Lookup].[TBL_PERIODS] ([PERIOD_ID], [NAME], [DESCRIPTION], [OCCURANCE_PERMONTH]) VALUES (3, N'Weekly', N'Each Week', 4)
GO
INSERT [Lookup].[TBL_PERIODS] ([PERIOD_ID], [NAME], [DESCRIPTION], [OCCURANCE_PERMONTH]) VALUES (4, N'Bi Weekly', N'Twice a Week', 8)
GO
INSERT [Lookup].[TBL_USER_TYPE] ([USERTYPE_ID], [NAME]) VALUES (1, N'Subscriber')
GO
INSERT [Lookup].[TBL_USER_TYPE] ([USERTYPE_ID], [NAME]) VALUES (2, N'Courier')
GO
SET IDENTITY_INSERT [Person].[TBL_USERS] ON 
GO
INSERT [Person].[TBL_USERS] ([USERS_ID], [USERNAME], [PASSWORDHASH], [EMAIL], [PHONE], [ADDRESS], [USERTYPE_ID]) VALUES (3, N'Amir Al Farooq', N'NONE', N'alfaroo@yahoo.com', NULL, NULL, 2)
GO
INSERT [Person].[TBL_USERS] ([USERS_ID], [USERNAME], [PASSWORDHASH], [EMAIL], [PHONE], [ADDRESS], [USERTYPE_ID]) VALUES (4, N'Abbas Haider', N'None', N'Abbas@haider.com', NULL, NULL, 1)
GO
SET IDENTITY_INSERT [Person].[TBL_USERS] OFF
GO
/****** Object:  Index [IDX_TBL_DELIVERY_DETAILS_ORDER_ID]    Script Date: 3/16/2024 8:18:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_TBL_DELIVERY_DETAILS_ORDER_ID] ON [Deliveries].[TBL_DELIVERY_DETAILS]
(
	[ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_TBL_DELIVERY_LOGS_DELIVERY_DETAILS_ID]    Script Date: 3/16/2024 8:18:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_TBL_DELIVERY_LOGS_DELIVERY_DETAILS_ID] ON [Deliveries].[TBL_DELIVERY_LOGS]
(
	[DELIVERY_DETAILS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_TBL_ORDER_ITEMS_ORDER_ID]    Script Date: 3/16/2024 8:18:50 PM ******/
CREATE NONCLUSTERED INDEX [IDX_TBL_ORDER_ITEMS_ORDER_ID] ON [Deliveries].[TBL_ORDER_ITEMS]
(
	[ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [Deliveries].[TBL_DELIVERY_DETAILS] ADD  CONSTRAINT [DF__TBL_DELIV__CONFI__3B75D760]  DEFAULT ((0)) FOR [CONFIRMATION]
GO
ALTER TABLE [Deliveries].[TBL_DELIVERY_ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_TBL_DELIVERYADDRESS_TBL_ADDRESSTYPE] FOREIGN KEY([ADDRESSTYPE_ID])
REFERENCES [Lookup].[TBL_ADDRESS_TYPE] ([ADDRESSTYPE_ID])
GO
ALTER TABLE [Deliveries].[TBL_DELIVERY_ADDRESS] CHECK CONSTRAINT [FK_TBL_DELIVERYADDRESS_TBL_ADDRESSTYPE]
GO
ALTER TABLE [Deliveries].[TBL_DELIVERY_ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_TBL_DELIVERYADDRESS_TBL_DELIVERY_DETAILS] FOREIGN KEY([DELIVERY_DETAILS_ID])
REFERENCES [Deliveries].[TBL_DELIVERY_DETAILS] ([DELIVERY_DETAILS_ID])
GO
ALTER TABLE [Deliveries].[TBL_DELIVERY_ADDRESS] CHECK CONSTRAINT [FK_TBL_DELIVERYADDRESS_TBL_DELIVERY_DETAILS]
GO
ALTER TABLE [Deliveries].[TBL_DELIVERY_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK__TBL_DELIV__ORDER__3C69FB99] FOREIGN KEY([ORDER_ID])
REFERENCES [Deliveries].[TBL_ORDERS] ([ORDER_ID])
GO
ALTER TABLE [Deliveries].[TBL_DELIVERY_DETAILS] CHECK CONSTRAINT [FK__TBL_DELIV__ORDER__3C69FB99]
GO
ALTER TABLE [Deliveries].[TBL_DELIVERY_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_TBL_DELIVERY_DETAILS_TBL_DELIVERY_STATUS] FOREIGN KEY([DELIVERY_STATUS])
REFERENCES [Lookup].[TBL_DELIVERY_STATUS] ([DELIVERYSTATUS_ID])
GO
ALTER TABLE [Deliveries].[TBL_DELIVERY_DETAILS] CHECK CONSTRAINT [FK_TBL_DELIVERY_DETAILS_TBL_DELIVERY_STATUS]
GO
ALTER TABLE [Deliveries].[TBL_DELIVERY_LOGS]  WITH CHECK ADD  CONSTRAINT [FK__TBL_DELIV__DELIV__3D5E1FD2] FOREIGN KEY([DELIVERY_DETAILS_ID])
REFERENCES [Deliveries].[TBL_DELIVERY_DETAILS] ([DELIVERY_DETAILS_ID])
GO
ALTER TABLE [Deliveries].[TBL_DELIVERY_LOGS] CHECK CONSTRAINT [FK__TBL_DELIV__DELIV__3D5E1FD2]
GO
ALTER TABLE [Deliveries].[TBL_DELIVERY_LOGS]  WITH CHECK ADD  CONSTRAINT [FK_TBL_DELIVERY_LOGS_ACTIVITY_TYPE] FOREIGN KEY([ACTIVITY_TYPE_ID])
REFERENCES [Lookup].[TBL_ACTIVITY_TYPE] ([ACTIVITY_TYPE_ID])
GO
ALTER TABLE [Deliveries].[TBL_DELIVERY_LOGS] CHECK CONSTRAINT [FK_TBL_DELIVERY_LOGS_ACTIVITY_TYPE]
GO
ALTER TABLE [Deliveries].[TBL_ORDER_ITEMS]  WITH CHECK ADD FOREIGN KEY([ITEM_ID])
REFERENCES [Deliveries].[TBL_ITEMS] ([ITEMS_ID])
GO
ALTER TABLE [Deliveries].[TBL_ORDER_ITEMS]  WITH CHECK ADD  CONSTRAINT [FK__TBL_ORDER__ORDER__403A8C7D] FOREIGN KEY([ORDER_ID])
REFERENCES [Deliveries].[TBL_ORDERS] ([ORDER_ID])
GO
ALTER TABLE [Deliveries].[TBL_ORDER_ITEMS] CHECK CONSTRAINT [FK__TBL_ORDER__ORDER__403A8C7D]
GO
ALTER TABLE [Deliveries].[TBL_ORDERS]  WITH CHECK ADD  CONSTRAINT [FK__TBL_ORDER__USER___412EB0B6] FOREIGN KEY([USER_ID])
REFERENCES [Person].[TBL_USERS] ([USERS_ID])
GO
ALTER TABLE [Deliveries].[TBL_ORDERS] CHECK CONSTRAINT [FK__TBL_ORDER__USER___412EB0B6]
GO
ALTER TABLE [Person].[TBL_USERS]  WITH CHECK ADD  CONSTRAINT [FK_TBL_USERS_TBL_USER_TYPE] FOREIGN KEY([USERTYPE_ID])
REFERENCES [Lookup].[TBL_USER_TYPE] ([USERTYPE_ID])
GO
ALTER TABLE [Person].[TBL_USERS] CHECK CONSTRAINT [FK_TBL_USERS_TBL_USER_TYPE]
GO
ALTER TABLE [Person].[TBL_USERS_ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_TBL_ADDRESS_TBL_ADDRESSTYPE] FOREIGN KEY([ADDRESSTYPE_ID])
REFERENCES [Lookup].[TBL_ADDRESS_TYPE] ([ADDRESSTYPE_ID])
GO
ALTER TABLE [Person].[TBL_USERS_ADDRESS] CHECK CONSTRAINT [FK_TBL_ADDRESS_TBL_ADDRESSTYPE]
GO
ALTER TABLE [Person].[TBL_USERS_ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_TBL_ADDRESS_TBL_USERS] FOREIGN KEY([USER_ID])
REFERENCES [Person].[TBL_USERS] ([USERS_ID])
GO
ALTER TABLE [Person].[TBL_USERS_ADDRESS] CHECK CONSTRAINT [FK_TBL_ADDRESS_TBL_USERS]
GO
ALTER TABLE [Schedule].[TBL_SCHEDULER]  WITH CHECK ADD  CONSTRAINT [FK__TBL_SCHED__ASSIG__35BCFE0A] FOREIGN KEY([ASSIGNED_TO])
REFERENCES [Person].[TBL_USERS] ([USERS_ID])
GO
ALTER TABLE [Schedule].[TBL_SCHEDULER] CHECK CONSTRAINT [FK__TBL_SCHED__ASSIG__35BCFE0A]
GO
ALTER TABLE [Schedule].[TBL_SCHEDULER]  WITH CHECK ADD  CONSTRAINT [FK_TBL_SCHEDULER_TBL_PERIODS] FOREIGN KEY([PERIOD_ID])
REFERENCES [Lookup].[TBL_PERIODS] ([PERIOD_ID])
GO
ALTER TABLE [Schedule].[TBL_SCHEDULER] CHECK CONSTRAINT [FK_TBL_SCHEDULER_TBL_PERIODS]
GO
ALTER TABLE [Schedule].[TBL_SCHEDULER]  WITH CHECK ADD  CONSTRAINT [FK_TBL_SCHEDULER_TBL_SCHEDULESTATUS] FOREIGN KEY([SCHEDULESTATUS_ID])
REFERENCES [Lookup].[TBL_SCHEDULE_STATUS] ([SCHEDULESTATUS_ID])
GO
ALTER TABLE [Schedule].[TBL_SCHEDULER] CHECK CONSTRAINT [FK_TBL_SCHEDULER_TBL_SCHEDULESTATUS]
GO
USE [master]
GO
ALTER DATABASE [DELIVERYDB] SET  READ_WRITE 
GO
